# Generated by Django 5.1.2 on 2024-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regional_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('population_size', models.PositiveBigIntegerField()),
                ('Area', models.FloatField()),
                ('Capital_city', models.CharField(max_length=300)),
                ('Flag', models.ImageField(upload_to='Flag')),
                ('email_address', models.EmailField(max_length=254)),
                ('map', models.ImageField(upload_to='map')),
                ('website', models.URLField()),
            ],
        ),
    ]
